import { useCallback, useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import SystemMonitorTrendChart from "./SystemMonitorTrendChart";

const API_BASE=import.meta.env.VITE_API_BASE_URL||"https://cleaning-task-api.onrender.com";
type Failure={id:string;actor_name?:string|null;actor_role?:string|null;source:string;action:string;page?:string|null;target_type?:string|null;target_name?:string|null;error_message?:string|null;metadata?:Record<string,unknown>|null;created_at:string};
type Trend={hour:string;operations:number;failures:number};
type Monitor={status:"normal"|"warning"|"critical";period_hours:number;summary:{operations:number;failures:number;auth_failures:number};source_counts:Record<string,number>;hourly_trend?:Trend[];failures:Failure[]};
type Group={key:string;source:string;action:string;page:string;error:string;count:number;latest:string;items:Failure[]};
const sources:Record<string,string>={admin:"PC管理",mobile:"スマホ管理",employee:"従業員",master:"最高管理者",system:"システム"};
const actions:Record<string,string>={login:"ログイン",login_failure:"ログイン失敗",auth_failure:"認証失敗",task_update:"清掃タスク編集",staff_update:"アカウント編集",staff_create:"アカウント作成",employee_operation:"従業員操作"};
const show=(v:unknown)=>v==null||v===''?'-':typeof v==='object'?JSON.stringify(v,null,2):String(v);

export default function MasterSystemMonitorPage(){
 const nav=useNavigate(),[data,setData]=useState<Monitor|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState<Failure|null>(null);
 const load=useCallback(async()=>{const token=localStorage.getItem('admin_access_token');if(!token){setError('ログイン情報がありません。');setLoading(false);return}setLoading(true);setError('');try{const r=await fetch(`${API_BASE}/api/master/system-monitor`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok){const b=await r.json().catch(()=>null);throw new Error(b?.detail||'監視情報を取得できませんでした。')}setData(await r.json())}catch(e){setData(null);setError(e instanceof Error?e.message:'監視情報を取得できませんでした。')}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const groups=useMemo<Group[]>(()=>{const m=new Map<string,Group>();for(const x of data?.failures||[]){const err=x.error_message||'失敗として記録',key=[x.source,x.page||'',x.action,err].join('|'),g=m.get(key);if(g){g.count++;g.items.push(x);if(new Date(x.created_at)>new Date(g.latest))g.latest=x.created_at}else m.set(key,{key,source:x.source,action:x.action,page:x.page||'-',error:err,count:1,latest:x.created_at,items:[x]})}return[...m.values()].sort((a,b)=>+new Date(b.latest)-+new Date(a.latest))},[data]);
 const status=error?'状態不明':data?.status==='critical'?'要確認':data?.status==='warning'?'注意':'正常';
 const badge=error?'bg-slate-100 text-slate-600':data?.status==='critical'?'bg-red-50 text-red-700':data?.status==='warning'?'bg-amber-50 text-amber-700':'bg-emerald-50 text-emerald-700';
 return <main className="mx-auto max-w-7xl px-6 py-8">
  <div className="flex items-start justify-between gap-4"><div><p className="text-sm font-semibold text-slate-500">MASTER ADMIN</p><h1 className="mt-1 text-3xl font-bold text-slate-900">システム監視</h1><p className="mt-2 text-sm text-slate-500">直近24時間の失敗操作・認証エラーを確認します。</p></div><button onClick={()=>nav('/master')} className="rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-700 shadow-sm">← 最高管理者画面へ戻る</button></div>
  {error?<div className="mt-6 rounded-2xl bg-red-50 p-5 text-sm text-red-700">{error}</div>:null}
  <div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="text-xs font-bold text-slate-400">システム状態</div><div className="mt-3"><span className={`rounded-full px-3 py-1.5 text-sm font-bold ${badge}`}>{loading?'確認中':status}</span></div></div>{[["24時間の操作",data?.summary.operations??0],["失敗操作",data?.summary.failures??0],["認証失敗",data?.summary.auth_failures??0]].map(([l,v])=><div key={String(l)} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="text-xs font-bold text-slate-400">{l}</div><div className="mt-2 text-3xl font-bold text-slate-900">{v}</div></div>)}</div>
  <SystemMonitorTrendChart data={data?.hourly_trend||[]}/>
  <section className="mt-4 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-bold text-slate-900">発生元別の失敗</h2><button onClick={()=>void load()} className="rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white">再読込</button></div><div className="mt-4 grid gap-3 sm:grid-cols-5">{Object.entries(sources).map(([k,l])=><div key={k} className="rounded-xl bg-slate-50 p-4"><div className="text-xs text-slate-500">{l}</div><div className="mt-1 text-xl font-bold">{data?.source_counts?.[k]??0}</div></div>)}</div></section>
  <section className="mt-4 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-bold">障害グループ</h2><p className="mt-1 text-xs text-slate-500">同じ発生元・画面・操作・エラーをまとめて表示します。行をクリックすると詳細を確認できます。</p></div><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr>{['最終発生','発生元','操作','エラー','件数'].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{loading?<tr><td colSpan={5} className="p-12 text-center text-slate-400">読み込み中...</td></tr>:!groups.length?<tr><td colSpan={5} className="p-12 text-center text-emerald-600">直近24時間に記録された失敗はありません</td></tr>:groups.map(g=><tr key={g.key} onClick={()=>setSelected(g.items[0])} className="cursor-pointer hover:bg-slate-50"><td className="whitespace-nowrap px-4 py-3">{new Date(g.latest).toLocaleString('ja-JP')}</td><td className="px-4 py-3">{sources[g.source]||g.source}<div className="text-xs text-slate-400">{g.page}</div></td><td className="px-4 py-3">{actions[g.action]||g.action}</td><td className="px-4 py-3 text-red-600">{g.error}</td><td className="px-4 py-3"><span className="rounded-full bg-red-50 px-2.5 py-1 text-xs font-bold text-red-700">{g.count}件</span></td></tr>)}</tbody></table></div></section>
  <section className="mt-4 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-bold">直近24時間の失敗履歴</h2></div><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr>{['日時','利用者','発生元','操作','エラー'].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{!loading&&(data?.failures||[]).map(x=><tr key={x.id} onClick={()=>setSelected(x)} className="cursor-pointer hover:bg-slate-50"><td className="whitespace-nowrap px-4 py-3">{new Date(x.created_at).toLocaleString('ja-JP')}</td><td className="px-4 py-3"><b>{x.actor_name||'不明'}</b><div className="text-xs text-slate-400">{x.actor_role||'-'}</div></td><td className="px-4 py-3">{sources[x.source]||x.source}<div className="text-xs text-slate-400">{x.page||'-'}</div></td><td className="px-4 py-3">{actions[x.action]||x.action}</td><td className="px-4 py-3 text-red-600">{x.error_message||'失敗として記録'}</td></tr>)}</tbody></table></div></section>
  {selected?<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 p-4" onClick={()=>setSelected(null)}><div className="max-h-[85vh] w-full max-w-2xl overflow-y-auto rounded-3xl bg-white p-6 shadow-xl" onClick={e=>e.stopPropagation()}><div className="flex justify-between gap-4"><div><p className="text-xs font-bold text-slate-400">障害詳細</p><h2 className="mt-1 text-2xl font-bold">{actions[selected.action]||selected.action}</h2></div><button onClick={()=>setSelected(null)} className="rounded-xl border px-3 py-2 text-sm font-semibold">閉じる</button></div><div className="mt-5 grid gap-3 rounded-2xl bg-slate-50 p-4 text-sm sm:grid-cols-2"><div><span className="text-slate-400">日時</span><div className="font-semibold">{new Date(selected.created_at).toLocaleString('ja-JP')}</div></div><div><span className="text-slate-400">利用者</span><div className="font-semibold">{selected.actor_name||'不明'} ({selected.actor_role||'-'})</div></div><div><span className="text-slate-400">発生元 / 画面</span><div className="font-semibold">{sources[selected.source]||selected.source} / {selected.page||'-'}</div></div><div><span className="text-slate-400">対象</span><div className="font-semibold">{selected.target_name||selected.target_type||'-'}</div></div></div><div className="mt-4 rounded-2xl bg-red-50 p-4 text-sm text-red-700"><b>エラー内容</b><div className="mt-1 whitespace-pre-wrap">{selected.error_message||'失敗として記録'}</div></div><div className="mt-4 rounded-2xl border p-4 text-sm"><b>技術情報</b><pre className="mt-2 overflow-x-auto whitespace-pre-wrap break-all text-xs text-slate-600">{show(selected.metadata)}</pre></div></div></div>:null}
 </main>
}
