import { useCallback, useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";

const API_BASE = import.meta.env.VITE_API_BASE_URL || "https://cleaning-task-api.onrender.com";
type Failure = { id:string; actor_name?:string|null; actor_role?:string|null; source:string; action:string; page?:string|null; target_name?:string|null; error_message?:string|null; created_at:string };
type Monitor = { status:"normal"|"warning"|"critical"; period_hours:number; summary:{operations:number;failures:number;auth_failures:number;latest_failure?:string|null}; source_counts:Record<string,number>; failures:Failure[] };
const sourceLabels:Record<string,string>={admin:"PC管理",mobile:"スマホ管理",employee:"従業員",master:"最高管理者",system:"システム"};
const actionLabels:Record<string,string>={login:"ログイン",login_failure:"ログイン失敗",auth_failure:"認証失敗",task_update:"清掃タスク編集",staff_update:"アカウント編集",staff_create:"アカウント作成"};

export default function MasterSystemMonitorPage(){
 const navigate=useNavigate(); const [data,setData]=useState<Monitor|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 const load=useCallback(async()=>{const token=localStorage.getItem("admin_access_token"); if(!token){setError("ログイン情報がありません。");setLoading(false);return;} setLoading(true);setError("");try{const r=await fetch(`${API_BASE}/api/master/system-monitor`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok){const b=await r.json().catch(()=>null);throw new Error(b?.detail||"監視情報を取得できませんでした。");}setData(await r.json());}catch(e){setError(e instanceof Error?e.message:"監視情報を取得できませんでした。");}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();},[load]);
 const statusLabel=data?.status==="critical"?"要確認":data?.status==="warning"?"注意":"正常";
 const statusClass=data?.status==="critical"?"bg-red-50 text-red-700":data?.status==="warning"?"bg-amber-50 text-amber-700":"bg-emerald-50 text-emerald-700";
 return <main className="mx-auto max-w-7xl px-6 py-8">
  <div className="flex items-start justify-between gap-4"><div><p className="text-sm font-semibold text-slate-500">MASTER ADMIN</p><h1 className="mt-1 text-3xl font-bold text-slate-900">システム監視</h1><p className="mt-2 text-sm text-slate-500">直近24時間の失敗操作・認証エラーを確認します。</p></div><button onClick={()=>navigate('/master')} className="shrink-0 rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-700 shadow-sm hover:bg-slate-50">← 最高管理者画面へ戻る</button></div>
  {error?<div className="mt-6 rounded-2xl bg-red-50 p-5 text-sm text-red-700">{error}</div>:null}
  <div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="text-xs font-bold text-slate-400">システム状態</div><div className="mt-3"><span className={`rounded-full px-3 py-1.5 text-sm font-bold ${statusClass}`}>{loading?'確認中':statusLabel}</span></div></div>{[["24時間の操作",data?.summary.operations??0],["失敗操作",data?.summary.failures??0],["認証失敗",data?.summary.auth_failures??0]].map(([l,v])=><div key={String(l)} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="text-xs font-bold text-slate-400">{l}</div><div className="mt-2 text-3xl font-bold text-slate-900">{v}</div></div>)}</div>
  <section className="mt-4 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-bold text-slate-900">発生元別の失敗</h2><button onClick={()=>void load()} className="rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white">再読込</button></div><div className="mt-4 grid gap-3 sm:grid-cols-5">{Object.entries(sourceLabels).map(([k,l])=><div key={k} className="rounded-xl bg-slate-50 p-4"><div className="text-xs text-slate-500">{l}</div><div className="mt-1 text-xl font-bold">{data?.source_counts?.[k]??0}</div></div>)}</div></section>
  <section className="mt-4 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-bold text-slate-900">直近24時間の失敗履歴</h2></div><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs font-bold text-slate-500"><tr><th className="px-4 py-3">日時</th><th className="px-4 py-3">利用者</th><th className="px-4 py-3">発生元</th><th className="px-4 py-3">操作</th><th className="px-4 py-3">エラー</th></tr></thead><tbody className="divide-y divide-slate-100">{loading?<tr><td colSpan={5} className="px-4 py-12 text-center text-slate-400">読み込み中...</td></tr>:!data?.failures.length?<tr><td colSpan={5} className="px-4 py-12 text-center text-emerald-600">直近24時間に記録された失敗はありません</td></tr>:data.failures.map(x=><tr key={x.id}><td className="whitespace-nowrap px-4 py-3">{new Date(x.created_at).toLocaleString('ja-JP')}</td><td className="px-4 py-3"><div className="font-semibold">{x.actor_name||'不明'}</div><div className="text-xs text-slate-400">{x.actor_role||'-'}</div></td><td className="px-4 py-3">{sourceLabels[x.source]||x.source}<div className="text-xs text-slate-400">{x.page||'-'}</div></td><td className="px-4 py-3">{actionLabels[x.action]||x.action}</td><td className="max-w-md px-4 py-3 text-red-600">{x.error_message||'失敗として記録'}</td></tr>)}</tbody></table></div></section>
 </main>;
}
