from pathlib import Path

p = Path('src/pages/admin/PayrollAttendancePage.tsx')
s = p.read_text()
old_head = '<thead className="bg-neutral-50 text-neutral-500"><tr><th className="px-3 py-2 text-left">施設</th><th className="px-3 py-2 text-left">完了部屋・時間内訳</th><th className="px-3 py-2 text-right">部屋数</th><th className="px-3 py-2 text-right">清掃報酬</th><th className="px-3 py-2 text-right">実働</th><th className="px-3 py-2 text-right">時給報酬</th><th className="px-3 py-2 text-right">保証調整</th><th className="px-3 py-2 text-right">交通費</th><th className="px-3 py-2 text-right">支給額</th><th className="px-3 py-2 text-right">操作</th></tr></thead>'
new_head = '<thead className="bg-neutral-50 text-neutral-500"><tr><th className="px-3 py-2 text-left">施設</th><th className="px-3 py-2 text-left">区分</th><th className="px-3 py-2 text-left">内訳</th><th className="px-3 py-2 text-right">部屋数</th><th className="px-3 py-2 text-right">清掃報酬</th><th className="px-3 py-2 text-right">実働</th><th className="px-3 py-2 text-right">時給報酬</th><th className="px-3 py-2 text-right">保証調整</th><th className="px-3 py-2 text-right">交通費</th><th className="px-3 py-2 text-right">支給額</th><th className="px-3 py-2 text-right">操作</th></tr></thead>'
old_body = '<tbody>{group.rows.map((r) => <tr key={r.id} className="border-t"><td className="px-3 py-3 font-medium">{r.facility || "-"}</td><td className="max-w-[360px] px-3 py-3 leading-5 text-neutral-600">{r.note || "-"}</td><td className="px-3 py-3 text-right">{r.room_count || 0}</td><td className="px-3 py-3 text-right">{yen(r.cleaning_amount)}</td><td className="px-3 py-3 text-right">{Number(r.actual_hours || 0).toFixed(2)}h</td><td className="px-3 py-3 text-right">{yen(r.hourly_amount)}</td><td className="px-3 py-3 text-right">{yen(r.adjustment_amount)}</td><td className="px-3 py-3 text-right">{yen(r.transportation_fee)}</td><td className="px-3 py-3 text-right font-semibold">{yen(r.final_amount)}</td><td className="px-3 py-3"><div className="flex justify-end gap-2"><button type="button" onClick={(e) => { e.stopPropagation(); setEditingPayroll(r); }} className="rounded-lg border bg-white px-3 py-1.5 font-medium">修正</button><button type="button" onClick={(e) => { e.stopPropagation(); void deletePayrollResult(r); }} className="rounded-lg border border-red-200 bg-red-50 px-3 py-1.5 font-medium text-red-600">削除</button></div></td></tr>)}</tbody>'
new_body = '''<tbody>{group.rows.flatMap((r) => {
  const parts = String(r.note || "").split(" / ").filter(Boolean);
  const pieceDetail = parts.filter((x) => !x.startsWith("時給対象:")).join(" / ") || "-";
  const hourlyDetail = parts.filter((x) => x.startsWith("時給対象:")).join(" / ") || (Number(r.actual_hours || 0) > 0 ? `${Number(r.actual_hours || 0).toFixed(2)}h × ${yen(r.hourly_rate)}` : "-");
  const hasPiece = Number(r.cleaning_amount || 0) !== 0 || Number(r.room_count || 0) > 0;
  const hasHourly = Number(r.hourly_amount || 0) !== 0 || Number(r.actual_hours || 0) > 0 || Number(r.adjustment_amount || 0) !== 0 || Number(r.transportation_fee || 0) !== 0;
  const lines: React.ReactNode[] = [];
  if (hasPiece) lines.push(<tr key={`${r.id}-piece`} className="border-t"><td className="px-3 py-3 font-medium">{r.facility || "-"}</td><td className="px-3 py-3"><span className="rounded-full border bg-neutral-50 px-2 py-1 font-semibold">単価分</span></td><td className="max-w-[360px] px-3 py-3 leading-5 text-neutral-600">{pieceDetail}</td><td className="px-3 py-3 text-right">{r.room_count || 0}</td><td className="px-3 py-3 text-right font-semibold">{yen(r.cleaning_amount)}</td><td className="px-3 py-3 text-right text-neutral-400">-</td><td className="px-3 py-3 text-right text-neutral-400">-</td><td className="px-3 py-3 text-right text-neutral-400">-</td><td className="px-3 py-3 text-right text-neutral-400">-</td><td className="px-3 py-3 text-right font-semibold">{yen(r.cleaning_amount)}</td><td className="px-3 py-3"><div className="flex justify-end gap-2"><button type="button" onClick={(e) => { e.stopPropagation(); setEditingPayroll(r); }} className="rounded-lg border bg-white px-3 py-1.5 font-medium">修正</button><button type="button" onClick={(e) => { e.stopPropagation(); void deletePayrollResult(r); }} className="rounded-lg border border-red-200 bg-red-50 px-3 py-1.5 font-medium text-red-600">削除</button></div></td></tr>);
  if (hasHourly) lines.push(<tr key={`${r.id}-hourly`} className="border-t bg-blue-50/30"><td className="px-3 py-3 font-medium">{r.facility || "-"}</td><td className="px-3 py-3"><span className="rounded-full border border-blue-200 bg-blue-50 px-2 py-1 font-semibold text-blue-700">時給換算分</span></td><td className="max-w-[360px] px-3 py-3 leading-5 text-neutral-600">{hourlyDetail}</td><td className="px-3 py-3 text-right text-neutral-400">-</td><td className="px-3 py-3 text-right text-neutral-400">-</td><td className="px-3 py-3 text-right">{Number(r.actual_hours || 0).toFixed(2)}h</td><td className="px-3 py-3 text-right font-semibold">{yen(r.hourly_amount)}</td><td className="px-3 py-3 text-right">{yen(r.adjustment_amount)}</td><td className="px-3 py-3 text-right">{yen(r.transportation_fee)}</td><td className="px-3 py-3 text-right font-semibold">{yen(Number(r.hourly_amount || 0) + Number(r.adjustment_amount || 0) + Number(r.transportation_fee || 0))}</td><td className="px-3 py-3"><div className="flex justify-end gap-2"><button type="button" onClick={(e) => { e.stopPropagation(); setEditingPayroll(r); }} className="rounded-lg border bg-white px-3 py-1.5 font-medium">修正</button><button type="button" onClick={(e) => { e.stopPropagation(); void deletePayrollResult(r); }} className="rounded-lg border border-red-200 bg-red-50 px-3 py-1.5 font-medium text-red-600">削除</button></div></td></tr>);
  return lines;
})}</tbody>'''
if old_head not in s or old_body not in s:
    raise SystemExit('target not found')
s = s.replace(old_head, new_head, 1).replace(old_body, new_body, 1)
p.write_text(s)
