import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";

const API_BASE = import.meta.env.VITE_API_BASE_URL || "https://cleaning-task-api.onrender.com";
const ORDER_MANAGEMENT_URL = import.meta.env.VITE_ORDER_MANAGEMENT_URL || "https://order-management-hoq5.onrender.com";
const MISSING_CLOCK_IN_HOUR = 10;
const MISSING_CLOCK_IN_MINUTE = 5;

type ShiftEntry = { id:string; start_time?:string; end_time?:string; assigned_area?:string; clock_in_at?:string|null; attendance_status?:string|null; attendance?:{status?:string|null;clock_in_at?:string|null}|null; staff_members?:{staff_name?:string} };
type ShiftDay = { id:string; shift_date:string; shift_entries?:ShiftEntry[] };
type PortalMessage = { id:string; target_date:string; message:string; updated_at?:string };
type OnBreakStaff = { id:string; name?:string; staff_code?:string; role?:string; break_started_at?:string|null };
type OrderDueSchedule = { id:string; order_no?:string; item_name?:string; quantity?:number|null; unit?:string|null; usage_place?:string|null; delivery_place?:string|null; supplier?:string|null; due_date:string };

function pad2(n:number){return String(n).padStart(2,"0")}
function toDateString(d:Date){return `${d.getFullYear()}-${pad2(d.getMonth()+1)}-${pad2(d.getDate())}`}
function formatTime(value?:string|null){if(!value)return "";if(/^\d{1,2}:\d{2}/.test(value))return value.slice(0,5);const d=new Date(value);return Number.isNaN(d.getTime())?value:`${pad2(d.getHours())}:${pad2(d.getMinutes())}`}
function formatBreakSince(iso?:string|null){if(!iso)return "休憩開始時刻 不明";const d=new Date(iso);return Number.isNaN(d.getTime())?"休憩開始時刻 不明":`${pad2(d.getHours())}:${pad2(d.getMinutes())} から`}
function isAfterMissingClockInTime(){const now=new Date();const t=new Date(now);t.setHours(MISSING_CLOCK_IN_HOUR,MISSING_CLOCK_IN_MINUTE,0,0);return now.getTime()>=t.getTime()}
function getClockInTime(e:ShiftEntry){return e.clock_in_at||e.attendance?.clock_in_at||""}
function isMissingClockIn(e:ShiftEntry,after:boolean){if(!after)return false;const s=e.attendance_status||e.attendance?.status||"";if(["clocked_in","checked_in","working","present"].includes(s))return false;if(["not_clocked_in","missing_clock_in","absent_unconfirmed"].includes(s))return true;return !getClockInTime(e)}

export default function AdminHomePage(){
 const navigate=useNavigate();const token=localStorage.getItem("admin_access_token")||"";const userRaw=localStorage.getItem("admin_user");
 const [todayDate,setTodayDate]=useState("");const [todayMessages,setTodayMessages]=useState<PortalMessage[]>([]);const [todayOrders,setTodayOrders]=useState<OrderDueSchedule[]>([]);const [todayShift,setTodayShift]=useState<ShiftDay|null>(null);const [onBreakStaff,setOnBreakStaff]=useState<OnBreakStaff[]>([]);const [loadingHome,setLoadingHome]=useState(true);const [nowTick,setNowTick]=useState(Date.now());
 const user=useMemo(()=>{try{return userRaw?JSON.parse(userRaw):null}catch{return null}},[userRaw]);
 const afterMissingClockInTime=useMemo(()=>{void nowTick;return isAfterMissingClockInTime()},[nowTick]);
 const missingClockInCount=useMemo(()=>(todayShift?.shift_entries||[]).filter(e=>isMissingClockIn(e,afterMissingClockInTime)).length,[todayShift,afterMissingClockInTime]);
 useEffect(()=>{if(!token||!userRaw){navigate("/admin/login");return}void fetchHome();const id=window.setInterval(()=>{setNowTick(Date.now());void fetchHome()},30000);return()=>window.clearInterval(id)},[token,userRaw,navigate]);
 async function authorizedFetch(input:string,init?:RequestInit){const res=await fetch(input,{...init,headers:{...(init?.headers||{}),Authorization:`Bearer ${token}`}});if(res.status===401||res.status===403){localStorage.removeItem("admin_access_token");localStorage.removeItem("admin_user");navigate("/admin/login");throw new Error("認証期限が切れました。")}return res}
 async function fetchHome(){try{setLoadingHome(true);const homeRes=await authorizedFetch(`${API_BASE}/api/admin-portal/home`);const data=await homeRes.json();const resolvedToday=data?.todayDate||toDateString(new Date());setTodayDate(resolvedToday);setTodayMessages(Array.isArray(data?.todayMessages)?data.todayMessages:[]);setTodayShift(data?.todayShift||null);setOnBreakStaff(Array.isArray(data?.onBreakStaff)?data.onBreakStaff:[]);const d=new Date(`${resolvedToday}T00:00:00`);const orderRes=await authorizedFetch(`${API_BASE}/api/admin-portal/order-due-schedules?year=${d.getFullYear()}&month=${d.getMonth()+1}`);const orderData=await orderRes.json();setTodayOrders(orderRes.ok&&Array.isArray(orderData?.items)?orderData.items.filter((i:any)=>i?.due_date===resolvedToday).map((i:any)=>({id:String(i.id),order_no:i.order_no||"",item_name:i.item_name||"",quantity:i.quantity??null,unit:i.unit??null,usage_place:i.usage_place??null,delivery_place:i.delivery_place??null,supplier:i.supplier??null,due_date:i.due_date})):[])}catch(e){console.error(e)}finally{setLoadingHome(false)}}
 return <div className="min-h-screen bg-slate-50 p-6"><div className="w-full space-y-6">
  <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><div><div className="text-sm text-slate-500">管理ポータル</div><h1 className="mt-1 text-3xl font-bold text-slate-900">ホーム</h1><div className="mt-2 text-sm text-slate-500">{user?.name?`${user.name} さんでログイン中`:"ログイン中"}</div></div><button onClick={()=>{localStorage.removeItem("admin_access_token");localStorage.removeItem("admin_user");navigate("/admin/login")}} className="rounded-2xl border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50">ログアウト</button></div></section>
  <section className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-4">
   <div onClick={()=>window.open(ORDER_MANAGEMENT_URL,"_blank","noopener,noreferrer")} className="cursor-pointer rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="text-lg font-bold">発注リスト</div><div className="mt-2 text-sm text-slate-500">発注依頼・納期・着荷状況を管理</div><div className="mt-4 text-sm font-semibold text-blue-600">ページを開く →</div></div>
   <div onClick={()=>window.open("https://gusk-property-management.onrender.com/opening","_blank","noopener,noreferrer")} className="cursor-pointer rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="text-lg font-bold">オープン管理</div><div className="mt-2 text-sm text-slate-500">新規物件の開業準備・進捗管理</div><div className="mt-4 text-sm font-semibold text-blue-600">ページを開く →</div></div>
   <div className="cursor-not-allowed rounded-2xl border border-slate-200 bg-slate-100 p-5 text-slate-400"><div className="text-lg font-bold">備品管理</div><div className="mt-2 text-sm">備品在庫・配置・補充管理</div><div className="mt-4 text-sm font-semibold">準備中</div></div>
   <div onClick={()=>{window.location.href="https://cleaning-task-admin.onrender.com/payroll"}} className="cursor-pointer rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="text-lg font-bold">給与・勤怠</div><div className="mt-2 text-sm text-slate-500">勤怠確認・給与計算</div><div className="mt-4 text-sm font-semibold text-blue-600">ページを開く →</div></div>
  </section>
  <div className="grid gap-6 lg:grid-cols-2">
   <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold text-slate-900">今日の連絡事項</h2><p className="mt-2 text-sm text-slate-500">登録・編集はスケジュールの全社カレンダーから行います</p><div className="mt-4 rounded-2xl bg-slate-50 px-4 py-4"><div className="text-sm font-semibold text-slate-800">{todayDate||"本日"}</div>{loadingHome?<div className="mt-3 text-sm text-slate-500">読み込み中...</div>:todayMessages.length===0?<div className="mt-3 text-sm text-slate-600">本日の連絡事項はありません。</div>:<div className="mt-3 space-y-3">{todayMessages.map(i=><div key={i.id} className="rounded-2xl bg-white px-4 py-4 text-sm text-slate-600 whitespace-pre-wrap">{i.message}</div>)}</div>}</div></section>
   <section className={`rounded-3xl border p-6 shadow-sm ${missingClockInCount>0?"border-rose-200 bg-rose-50":"border-slate-200 bg-white"}`}><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-bold text-slate-900">本日の社内スケジュール</h2><p className="mt-1 text-xs text-slate-500">10:05以降、Jinjer出勤打刻がないスタッフを未打刻表示します。</p></div><div className="flex items-center gap-2">{missingClockInCount>0?<span className="rounded-full bg-rose-600 px-3 py-0.5 text-xs font-bold text-white">未打刻 {missingClockInCount} 名</span>:null}<span className="rounded-full bg-slate-100 px-3 py-0.5 text-xs font-bold text-slate-700">{todayShift?.shift_entries?.length??0} 名</span></div></div><div className="mt-4 max-h-[480px] overflow-y-auto pr-1 grid grid-cols-1 gap-2 sm:grid-cols-2">{!todayShift?.shift_entries?.length?<div className="col-span-full rounded-2xl bg-slate-50 px-4 py-4 text-sm text-slate-500">本日のシフトはありません</div>:todayShift.shift_entries.map(e=>{const missing=isMissingClockIn(e,afterMissingClockInTime);const clockIn=getClockInTime(e);return <div key={e.id} className={`rounded-xl border px-3 py-2 ${missing?"border-rose-300 bg-rose-100 ring-2 ring-rose-100":"border-slate-200 bg-slate-50"}`}><div className="flex items-center justify-between gap-2"><div className="truncate text-sm font-bold text-slate-900">{e.staff_members?.staff_name||"-"}</div>{missing?<span className="rounded-full bg-rose-600 px-2 py-0.5 text-[10px] font-bold text-white">未打刻</span>:clockIn?<span className="rounded-full bg-emerald-100 px-2 py-0.5 text-[10px] font-bold text-emerald-700">打刻済</span>:null}</div><div className="mt-0.5 truncate text-xs text-slate-600">{e.start_time||"-"} 〜 {e.end_time||"-"} / {e.assigned_area||"-"}</div>{clockIn?<div className="mt-1 text-[11px] font-semibold text-emerald-700">出勤打刻 {formatTime(clockIn)}</div>:missing?<div className="mt-1 text-[11px] font-semibold text-rose-700">Jinjer出勤打刻なし</div>:null}</div>})}</div></section>
  </div>
  <section className="rounded-3xl border border-amber-200 bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold text-slate-900">本日の発注納期</h2><p className="mt-1 text-xs text-slate-500">本日が納期の発注を表示します。</p></div><div className="flex items-center gap-2"><span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-800">{todayOrders.length}件</span><button type="button" onClick={()=>window.open(ORDER_MANAGEMENT_URL,"_blank","noopener,noreferrer")} className="rounded-xl border border-amber-200 bg-amber-50 px-3 py-2 text-xs font-bold text-amber-900 hover:bg-amber-100">発注管理で確認 →</button></div></div>{loadingHome?<div className="mt-4 text-sm text-slate-500">読み込み中...</div>:todayOrders.length===0?<div className="mt-4 rounded-2xl bg-slate-50 px-4 py-4 text-sm text-slate-500">本日納期の発注はありません。</div>:<div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{todayOrders.map(i=><button key={i.id} type="button" onClick={()=>window.open(ORDER_MANAGEMENT_URL,"_blank","noopener,noreferrer")} className="rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-left hover:bg-amber-100"><div className="truncate font-bold text-slate-900">{i.item_name||"品名未設定"}</div><div className="mt-1 text-xs text-slate-600">数量：{i.quantity??"-"}{i.unit||""}</div><div className="mt-1 truncate text-xs text-slate-600">配送先：{i.delivery_place||i.usage_place||"未設定"}</div>{i.supplier?<div className="mt-1 truncate text-[11px] text-slate-500">仕入先：{i.supplier}</div>:null}</button>)}</div>}</section>
  <section className={`rounded-3xl border p-6 shadow-sm ${onBreakStaff.length>0?"border-amber-300 bg-amber-50":"border-slate-200 bg-white"}`}><div className="flex items-center justify-between gap-3"><h2 className="text-xl font-bold text-slate-900">現在 休憩中のスタッフ</h2><span className="text-xs text-slate-500">{onBreakStaff.length} 名 / 30秒ごとに更新</span></div><div className="mt-4">{onBreakStaff.length===0?<div className="rounded-2xl border border-slate-200 bg-white px-4 py-4 text-sm text-slate-500">現在 休憩中のスタッフはいません。</div>:<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{onBreakStaff.map(s=><div key={s.id} className="rounded-2xl border border-amber-300 bg-white px-4 py-3"><div className="font-bold text-slate-900">{s.name||"-"}</div><div className="mt-1 text-xs text-slate-500">{s.staff_code?`${s.staff_code} / `:""}{s.role||"-"}</div><div className="mt-2 text-sm text-amber-700">{formatBreakSince(s.break_started_at)}</div></div>)}</div>}</div></section>
 </div></div>
}
