import { useCallback, useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";

const API_BASE=import.meta.env.VITE_API_BASE_URL||"https://cleaning-task-api.onrender.com";
type Point={hour:string;operations:number;failures:number};
type DashboardData={period_hours:number;summary:{operations:number;failures:number};hourly_trend:Point[]};
type Failure={id:string;actor_name?:string;source?:string;action?:string;page?:string;error_message?:string;created_at?:string};
type MonitorData={failures?:Failure[]};

function Icon({name}:{name:"log"|"account"|"monitor"|"settings"}){const common={width:20,height:20,viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:1.8,strokeLinecap:"round" as const,strokeLinejoin:"round" as const};if(name==="log")return <svg {...common}><path d="M5 5h14M5 12h14M5 19h9"/><circle cx="3" cy="5" r=".5" fill="currentColor"/><circle cx="3" cy="12" r=".5" fill="currentColor"/><circle cx="3" cy="19" r=".5" fill="currentColor"/></svg>;if(name==="account")return <svg {...common}><circle cx="12" cy="8" r="3"/><path d="M5.5 19c.8-3.4 3-5 6.5-5s5.7 1.6 6.5 5"/><circle cx="12" cy="12" r="9"/></svg>;if(name==="monitor")return <svg {...common}><path d="M12 3 21 19H3L12 3Z"/><path d="M12 9v4M12 16h.01"/></svg>;return <svg {...common}><circle cx="12" cy="12" r="3"/><path d="M19 12a7 7 0 0 0-.1-1l2-1.5-2-3.4-2.4 1A8 8 0 0 0 15 6.2L14.7 4h-5.4L9 6.2a8 8 0 0 0-1.5.9l-2.4-1-2 3.4 2 1.5a7 7 0 0 0 0 2l-2 1.5 2 3.4 2.4-1a8 8 0 0 0 1.5.9l.3 2.2h5.4l.3-2.2a8 8 0 0 0 1.5-.9l2.4 1 2-3.4-2-1.5a7 7 0 0 0 .1-1Z"/></svg>}
const menus=[{icon:"log" as const,title:"ログ監査",description:"全画面の操作履歴を確認",to:"/master/audit"},{icon:"account" as const,title:"アカウント・権限監査",description:"権限と変更履歴を確認",to:"/master/accounts"},{icon:"monitor" as const,title:"システム監視",description:"エラー・異常状態を確認",to:"/master/system"},{icon:"settings" as const,title:"最高管理者設定",description:"最高管理者権限を管理",to:"/master/settings"}];

function Chart({data,mode}:{data:Point[];mode:"history"|"failure"}){const width=680,height=210,left=34,right=12,top=12,bottom=30;const values=data.map(p=>mode==="history"?p.operations:p.failures);const max=Math.max(1,...values);const x=(i:number)=>left+(data.length<=1?0:i*(width-left-right)/(data.length-1));const y=(v:number)=>top+(height-top-bottom)-(v/max)*(height-top-bottom);const points=data.map((p,i)=>`${x(i)},${y(mode==="history"?p.operations:p.failures)}`).join(" ");const color=mode==="history"?"#334155":"#ef4444";return <svg viewBox={`0 0 ${width} ${height}`} className="w-full"><line x1={left} x2={width-right} y1={height-bottom} y2={height-bottom} stroke="#e2e8f0"/><line x1={left} x2={width-right} y1={top+(height-top-bottom)/2} y2={top+(height-top-bottom)/2} stroke="#f1f5f9"/><polyline points={points} fill="none" stroke={color} strokeWidth="3" strokeLinejoin="round" strokeLinecap="round"/>{data.map((p,i)=>{const v=mode==="history"?p.operations:p.failures;return <g key={p.hour}><circle cx={x(i)} cy={y(v)} r={v?3.2:2} fill={color}><title>{`${new Date(p.hour).toLocaleString("ja-JP")} ${v}件`}</title></circle>{(i%6===0||i===data.length-1)?<text x={x(i)} y={height-8} textAnchor="middle" fontSize="10" fill="#94a3b8">{new Date(p.hour).toLocaleTimeString("ja-JP",{hour:"2-digit",minute:"2-digit"})}</text>:null}</g>})}</svg>}
function Metric({label,value,sub,tone="normal",status=false}:{label:string;value:string|number;sub:string;tone?:"normal"|"danger"|"warning"|"success";status?:boolean}){const valueClass=tone==="danger"?"text-red-600":tone==="warning"?"text-amber-600":tone==="success"?"text-emerald-600":"text-slate-900";const bg=status?(tone==="danger"?"border-red-100 bg-red-50/60":tone==="warning"?"border-amber-100 bg-amber-50/60":"border-emerald-100 bg-emerald-50/50"):"border-slate-200 bg-white";return <div className={`rounded-2xl border px-5 py-4 shadow-sm ${bg}`}><p className="text-xs font-bold text-slate-400">{label}</p><div className={`mt-2 flex items-center gap-2 text-2xl font-bold ${valueClass}`}>{status?<span className={`h-2.5 w-2.5 rounded-full ${tone==="danger"?"bg-red-500":tone==="warning"?"bg-amber-500":"bg-emerald-500"}`}/>:null}{value}</div><p className="mt-1 text-xs text-slate-400">{sub}</p></div>}

export default function MasterAdminSystemPage(){const [data,setData]=useState<DashboardData|null>(null);const [failuresList,setFailuresList]=useState<Failure[]>([]);const [error,setError]=useState("");const [updatedAt,setUpdatedAt]=useState<Date|null>(null);const load=useCallback(async()=>{const token=localStorage.getItem("admin_access_token");if(!token)return;try{const headers={Authorization:`Bearer ${token}`};const [dashboard,monitor]=await Promise.all([fetch(`${API_BASE}/api/master/dashboard`,{headers}),fetch(`${API_BASE}/api/master/system-monitor`,{headers})]);if(!dashboard.ok)throw new Error();setData(await dashboard.json());if(monitor.ok){const m:MonitorData=await monitor.json();setFailuresList((m.failures||[]).slice(0,3))}setUpdatedAt(new Date());setError("")}catch{setError("システム情報を取得できませんでした。")}},[]);useEffect(()=>{void load()},[load]);const operations=data?.summary.operations||0;const failures=data?.summary.failures||0;const failureRate=useMemo(()=>operations?Math.round((failures/operations)*1000)/10:0,[operations,failures]);const status=failures===0?"正常":failures<10?"注意":"要確認";const statusTone=failures===0?"success":failures<10?"warning":"danger";
return <main className="min-h-screen bg-slate-50/60"><div className="mx-auto max-w-[1480px] px-6 py-8 lg:px-10"><header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold tracking-[.16em] text-slate-400">MASTER ADMIN</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-900">システム管理</h1><p className="mt-2 text-sm text-slate-500">システム全体の稼働状況・監査・権限を管理します。</p></div><div className="flex items-center gap-3"><div className="text-right"><div className="text-xs font-semibold text-slate-400">最終更新</div><div className="mt-1 text-xs text-slate-600">{updatedAt?updatedAt.toLocaleTimeString("ja-JP",{hour:"2-digit",minute:"2-digit"}):"-"}</div></div><button onClick={()=>void load()} className="rounded-xl border border-slate-200 bg-white px-4 py-2 text-xs font-bold text-slate-700 shadow-sm hover:bg-slate-50">再読込</button><span className="rounded-full bg-slate-900 px-4 py-2 text-xs font-bold text-white">最高管理者専用</span></div></header>{error?<div className="mt-5 rounded-xl border border-red-100 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>:null}
<section className="mt-7"><div className="mb-3 flex items-end justify-between"><div><h2 className="text-sm font-bold text-slate-900">システムステータス</h2><p className="mt-1 text-xs text-slate-400">直近24時間の稼働状況</p></div><Link to="/master/system" className="text-xs font-bold text-slate-500 hover:text-slate-900">詳細を確認 →</Link></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="システム状態" value={status} sub={failures?`${failures}件の失敗ログを検出`:"失敗ログはありません"} tone={statusTone} status/><Metric label="操作数" value={data?operations:"-"} sub="直近24時間"/><Metric label="エラー" value={data?failures:"-"} sub="直近24時間" tone={failures?"danger":"normal"}/><Metric label="エラー率" value={data?`${failureRate}%`:"-"} sub="全操作に対する失敗率" tone={failureRate?"danger":"normal"}/></div></section>
<section className="mt-7"><div className="mb-3"><h2 className="text-sm font-bold text-slate-900">稼働ログ</h2><p className="mt-1 text-xs text-slate-400">1時間ごとの操作・エラー推移</p></div><div className="grid gap-4 lg:grid-cols-2"><Link to="/master/audit" className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition hover:border-slate-300 hover:shadow"><div className="flex justify-between"><div><h3 className="font-bold text-slate-900">操作履歴</h3><p className="mt-1 text-xs text-slate-400">監査ログ件数</p></div><div className="text-right"><div className="text-3xl font-bold text-slate-900">{data?operations:"-"}</div><div className="text-xs text-slate-400">24時間</div></div></div><div className="mt-4"><Chart data={data?.hourly_trend||[]} mode="history"/></div></Link><Link to="/master/system" className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition hover:border-slate-300 hover:shadow"><div className="flex justify-between"><div><h3 className="font-bold text-slate-900">エラー推移</h3><p className="mt-1 text-xs text-slate-400">失敗ログ件数</p></div><div className="text-right"><div className="text-3xl font-bold text-red-600">{data?failures:"-"}</div><div className="text-xs text-slate-400">失敗率 {failureRate}%</div></div></div><div className="mt-4"><Chart data={data?.hourly_trend||[]} mode="failure"/></div></Link></div></section>
{failuresList.length?<section className="mt-7"><div className="mb-3 flex items-end justify-between"><div><h2 className="text-sm font-bold text-slate-900">要確認</h2><p className="mt-1 text-xs text-slate-400">直近のエラーを表示しています。</p></div><Link to="/master/system" className="text-xs font-bold text-slate-500 hover:text-slate-900">すべて確認 →</Link></div><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{failuresList.map((f,i)=><Link to="/master/system" key={f.id||i} className={`grid gap-2 px-5 py-4 transition hover:bg-slate-50 md:grid-cols-[150px_1fr_1fr_110px] md:items-center ${i?"border-t border-slate-100":""}`}><div className="flex items-center gap-2 text-xs font-bold text-red-600"><span className="h-2 w-2 rounded-full bg-red-500"/>エラー</div><div><div className="text-sm font-bold text-slate-800">{f.action||"不明な操作"}</div><div className="mt-1 text-xs text-slate-400">{f.source||"system"} / {f.page||"-"}</div></div><div className="truncate text-xs text-slate-500">{f.error_message||"詳細情報なし"}</div><div className="text-right text-xs text-slate-400">{f.created_at?new Date(f.created_at).toLocaleString("ja-JP",{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"}):"-"}</div></Link>)}</div></section>:null}
<section className="mt-7 pb-10"><div className="mb-3"><h2 className="text-sm font-bold text-slate-900">管理メニュー</h2><p className="mt-1 text-xs text-slate-400">監査・アカウント・システム設定</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{menus.map(m=><Link key={m.title} to={m.to} className="group flex items-center gap-4 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm transition hover:border-slate-300 hover:shadow"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-slate-100 text-slate-600 group-hover:bg-slate-900 group-hover:text-white"><Icon name={m.icon}/></div><div className="min-w-0"><h3 className="text-sm font-bold text-slate-900">{m.title}</h3><p className="mt-1 truncate text-xs text-slate-400">{m.description}</p></div><span className="ml-auto text-lg text-slate-300">›</span></Link>)}</div></section></div></main>}
